### PR TITLE
Fixed offline bug for WebOS

### PR DESCRIPTION
**Pull request by rkokkelk**
Okay, so I've redesigned the app. Instead of a network scan which is executed every 10 seconds, the app tries to connect to TV using the stored info (IP, key). 

Every action will try to connect to the TV, a timeout is set to 2seconds, so if the TV is offline this is notified in that time. Otherwise it connects and the action is executed. The `tvs` dictionary is used to keep track of the online remotes. If a TV is still online it uses the stored TV remote, otherwise it tries to connect. If the TV remote disconnects it is also removed from the `tvs` dict. 

However, in order for the connect to work on every action I have removed the `module.exports.setUnavailable` and `module.exports.setAvailable` functions. Because if the TV is offline, the actions are not executed and therefore the app never tries to connect to the TV. I hope this is not against the implementation designs of the driver.

Please let me know what you think!

### CODE REVIEW

**Comment by WeeJeWel** [comment]
Thanks! I will test it this weekend. (Also xbox)

**Comment by WeeJeWel** [comment]
(Sorry, I haven't got the time yet - but I didn't forget this PR!)

**Comment by rkokkelk** [comment]
My apologies, during the initial development my system was already paired. So totally forgot to test that functionality. It should all work appropriately now.

**Comment by JesperJanssen** [comment]
@WeeJeWel: Any idea when the update of the app will be reviewed? I can't wait to try it out on my LG tv.

**Comment by JesperJanssen** [comment]
@WeeJeWel; Any update about this app improvement?

**Comment by WeeJeWel** [comment]
@JesperJanssen We're rewriting Homey's internal Apps SDK. When that is finished (give or take a few weeks) I'm going to rewrite this app entirely, and add support for WebOS 3 as well.

**Pull request closed without merging**
